/// Simple two-language localization (RU / EN), switchable in Settings.
library;

class L10n {
  static String lang = 'ru';

  static String t(String key) =>
      _map[lang]?[key] ?? _map['en']![key] ?? key;

  static const Map<String, Map<String, String>> _map = {
    'ru': {
      'appTitle': 'КОШКИН ДЕНЬ',
      'subtitle': 'Комикс-тренажёр будущего котовладельца',
      'menuPlay': 'ИГРАТЬ',
      'menuSettings': 'Настройки',
      'menuHelp': 'Как ухаживать',
      'settingsTitle': 'Настройки',
      'sfx': 'Звуковые эффекты',
      'musicTitle': 'Фоновая музыка',
      'musicName': '«Kitten on the Keys» · «The Entertainer» (рэгтайм, public domain)',
      'langTitle': 'Язык / Language',
      'back': 'Назад',
      'helpTitle': 'Памятка по уходу за кошками',
      'helpBody':
          'Ваш день с Муркой и котёнком Барсиком длится 10 минут — с утра до ночи.\n\n'
          '• МИСКА: кошки едят 2–3 раза в день. Заметили пузырь с миской — '
          'нажмите на миски и покормите.\n'
          '• ЛОТОК: чистите после использования. Кошка откажется ходить в грязный лоток '
          'и будет кричать.\n'
          '• ИГРА: котятам нужно играть часто, взрослым — хотя бы 2 раза в день. '
          'Нажмите на корзину с игрушками.\n'
          '• КОГТИ: кошки точат когти — это природа! Если кошка царапает диван или обои, '
          'остановите её нажатием и предложите когтеточку.\n'
          '• СТОЛ: кошки любят скидывать вещи. Успейте остановить!\n'
          '• ЛАСКА: гладьте кошек — нажмите на кошку, когда она просит внимания.\n'
          '• ПТИЧКИ: наблюдение за птицами в окне — любимое кошачье ТВ. Не мешайте!\n\n'
          'Выполняйте задания вовремя, иначе кошки начнут ОРАТЬ. Удачи!',
      'pauseTitle': 'Пауза',
      'resume': 'Продолжить',
      'restart': 'Заново',
      'quitToMenu': 'В меню',
      'scoreLabel': 'Очки',
      'timeLabel': 'Время',
      'tasksLabel': 'Задания',
      'task_feed': 'Покорми кошек',
      'task_litter': 'Почисти лоток',
      'task_play': 'Поиграй с кошками',
      'task_attention': 'Погладь',
      'task_mischief': 'Останови шалость!',
      'task_door': 'Открой дверь — звонок!',
      'task_toy': 'Достань мышку из-под дивана',
      'tip_post': 'Совет: когтеточка спасает мебель. Кошка поточила когти — все довольны!',
      'tip_feed': 'Совет: кормите кошек по расписанию 2–3 раза в день.',
      'tip_litter': 'Совет: грязный лоток — причина №1 кошачьих «сюрпризов» мимо.',
      'tip_play': 'Совет: 15 минут игры в день — и кошка не будет портить вещи от скуки.',
      'tip_attention': 'Совет: кошки тоже нуждаются в ласке. Но только когда САМИ хотят.',
      'tip_box': 'Коробка! Любая кошка считает: «Если я помещаюсь — я сажусь».',
      'tip_birds': 'Кошки смотрят на птичек — это их телевизор. Полезно для психики!',
      'tip_door_none': 'За дверью никого нет.',
      'tip_pickup': 'Уберите осколки сразу — кошки могут пораниться!',
      'tip_zoomies': 'Вечерние «тыгыдыки» — норма! Кошки выплёскивают энергию.',
      'tip_sleep': 'Кошки спят 12–16 часов в день. Не будите — это святое.',
      'tip_storm': 'Гроза! Кошки боятся грома — не трогайте их, пусть спрячутся.',
      'tip_fly': 'Муха в доме! Лучший бесплатный тренажёр для кошек.',
      'tip_flower': 'Кошки обожают ронять горшки. Не ставьте цветы на край — и проверяйте, не ядовиты ли они для кошек!',
      'tip_accident': 'Лужа?! Кошка отказалась идти в грязный лоток. Чистите лоток вовремя!',
      'fx_crash': 'ХРЯСЬ!',
      'fx_meow': 'МЯУ!',
      'fx_yowl': 'МЯ-Я-ЯУ!!!',
      'fx_purr': 'муррр…',
      'fx_scratch': 'вжик-вжик',
      'fx_ding': 'ДЗЫНЬ!',
      'fx_boom': 'БА-БАХ!',
      'fx_oops': 'УПС…',
      'fx_no': 'НЕЛЬЗЯ!',
      'fx_zzz': 'хррр…',
      'cat_adult': 'Мурка',
      'cat_kitten': 'Барсик',
      'phase_morning': 'Утро',
      'phase_day': 'День',
      'phase_evening': 'Вечер',
      'phase_night': 'Ночь',
      'result_win': 'ДЕНЬ ПРОЖИТ!',
      'result_lose': 'КОШКИ НЕДОВОЛЬНЫ…',
      'result_done': 'Заданий выполнено',
      'result_failed': 'Провалено',
      'result_damage': 'Испорчено вещей',
      'result_learned': 'Чему вы научились:',
      'learned_1': 'Кормить по расписанию',
      'learned_2': 'Держать лоток чистым',
      'learned_3': 'Играть каждый день',
      'learned_4': 'Направлять когти на когтеточку',
      'learned_5': 'Уважать кошачьи ритуалы',
      'play_again': 'Играть ещё',
      'win_3': 'Идеальный котовладелец! 3 звезды!',
      'win_2': 'Отлично! Кошки почти всем довольны.',
      'win_1': 'Неплохо, но есть чему поучиться.',
      'win_0': 'Кошки объявили забастовку. Попробуйте ещё раз!',
      'intro_text': 'Утро! Мурка и Барсик уже проснулись.\n'
          'Нажимайте на предметы и кошек, чтобы ухаживать за ними.\n'
          'Продержитесь день — 10 минут!',
      'start': 'Начать день',
      'mood': 'Настроение',
      'howto_title': 'Как играть:',
      'howto_feed': '🍗 Миски (слева) — покормить',
      'howto_litter': '🧹 Лоток (справа у двери) — почистить',
      'howto_play': '🧶 Корзина игрушек — поиграть',
      'howto_cat': '🐾 Кошка — погладить или остановить шалость',
      'howto_task': '👆 Или нажмите на карточку задания — владелец сам всё сделает',
      'hint_feed': 'нажмите на миски',
      'hint_litter': 'нажмите на лоток',
      'hint_play': 'нажмите на корзину с игрушками',
      'hint_attention': 'нажмите на кошку',
      'hint_mischief': 'нажмите на кошку-хулигана!',
      'hint_door': 'нажмите на дверь',
      'hint_toy': 'нажмите на диван',
    },
    'en': {
      'appTitle': "A CAT'S DAY",
      'subtitle': 'A comic-style trainer for future cat owners',
      'menuPlay': 'PLAY',
      'menuSettings': 'Settings',
      'menuHelp': 'Cat care guide',
      'settingsTitle': 'Settings',
      'sfx': 'Sound effects',
      'musicTitle': 'Background music',
      'musicName': '"Kitten on the Keys" · "The Entertainer" (ragtime, public domain)',
      'langTitle': 'Язык / Language',
      'back': 'Back',
      'helpTitle': 'Cat care guide',
      'helpBody':
          'Your day with Misty and kitten Biscuit lasts 10 minutes — morning to night.\n\n'
          '• BOWL: cats eat 2–3 times a day. See a food bubble — tap the bowls to feed.\n'
          '• LITTER BOX: clean it after use. Cats refuse a dirty box and will yell about it.\n'
          '• PLAY: kittens need frequent play, adults at least twice a day. Tap the toy basket.\n'
          '• CLAWS: scratching is natural! If a cat attacks the sofa or wallpaper, '
          'stop it with a tap and offer the scratching post.\n'
          '• TABLE: cats love pushing things off. Be quick!\n'
          '• AFFECTION: pet the cats — tap a cat when it asks for attention.\n'
          '• BIRDS: bird-watching is cat TV. Let them enjoy it!\n\n'
          'Complete tasks in time or the cats will start YELLING. Good luck!',
      'pauseTitle': 'Paused',
      'resume': 'Resume',
      'restart': 'Restart',
      'quitToMenu': 'Main menu',
      'scoreLabel': 'Score',
      'timeLabel': 'Time',
      'tasksLabel': 'Tasks',
      'task_feed': 'Feed the cats',
      'task_litter': 'Clean the litter box',
      'task_play': 'Play with the cats',
      'task_attention': 'Pet',
      'task_mischief': 'Stop the mischief!',
      'task_door': 'Doorbell — open the door!',
      'task_toy': 'Fetch the mouse from under the sofa',
      'tip_post': 'Tip: a scratching post saves your furniture. Everybody wins!',
      'tip_feed': 'Tip: feed cats on a schedule, 2–3 times a day.',
      'tip_litter': 'Tip: a dirty litter box is the #1 cause of accidents.',
      'tip_play': 'Tip: 15 minutes of play a day keeps boredom-mischief away.',
      'tip_attention': 'Tip: cats need affection too. But only when THEY want it.',
      'tip_box': 'A box! Cat logic: "If I fits — I sits."',
      'tip_birds': 'Bird-watching is cat TV. Great for their minds!',
      'tip_door_none': 'Nobody at the door.',
      'tip_pickup': 'Pick up shards right away — cats can get hurt!',
      'tip_zoomies': 'Evening zoomies are normal! Cats burn off energy.',
      'tip_sleep': 'Cats sleep 12–16 hours a day. Never wake them — it is sacred.',
      'tip_storm': 'Thunderstorm! Cats fear thunder — let them hide, it is normal.',
      'tip_fly': 'A fly got in! The best free cat exercise machine.',
      'tip_flower': 'Cats love knocking pots off. Keep plants away from edges — and check they are not toxic to cats!',
      'tip_accident': 'A puddle?! The cat refused the dirty litter box. Clean it in time!',
      'fx_crash': 'CRASH!',
      'fx_meow': 'MEOW!',
      'fx_yowl': 'MEE-OW-W!!!',
      'fx_purr': 'purrr…',
      'fx_scratch': 'scritch-scratch',
      'fx_ding': 'DING!',
      'fx_boom': 'KA-BOOM!',
      'fx_oops': 'OOPS…',
      'fx_no': 'NO!',
      'fx_zzz': 'zzz…',
      'cat_adult': 'Misty',
      'cat_kitten': 'Biscuit',
      'phase_morning': 'Morning',
      'phase_day': 'Day',
      'phase_evening': 'Evening',
      'phase_night': 'Night',
      'result_win': 'DAY SURVIVED!',
      'result_lose': 'THE CATS ARE NOT AMUSED…',
      'result_done': 'Tasks completed',
      'result_failed': 'Failed',
      'result_damage': 'Things ruined',
      'result_learned': 'What you learned:',
      'learned_1': 'Feed on schedule',
      'learned_2': 'Keep the litter box clean',
      'learned_3': 'Play every day',
      'learned_4': 'Redirect claws to the post',
      'learned_5': 'Respect cat rituals',
      'play_again': 'Play again',
      'win_3': 'Purr-fect cat owner! 3 stars!',
      'win_2': 'Great! The cats are mostly pleased.',
      'win_1': 'Not bad, but there is room to grow.',
      'win_0': 'The cats are on strike. Try again!',
      'intro_text': 'Morning! Misty and Biscuit are already awake.\n'
          'Tap objects and cats to take care of them.\n'
          'Survive the day — 10 minutes!',
      'start': 'Start the day',
      'mood': 'Mood',
      'howto_title': 'How to play:',
      'howto_feed': '🍗 Bowls (left) — feed',
      'howto_litter': '🧹 Litter box (by the door) — clean',
      'howto_play': '🧶 Toy basket — play',
      'howto_cat': '🐾 A cat — pet it or stop mischief',
      'howto_task': '👆 Or tap a task card — the owner does it himself',
      'hint_feed': 'tap the bowls',
      'hint_litter': 'tap the litter box',
      'hint_play': 'tap the toy basket',
      'hint_attention': 'tap the cat',
      'hint_mischief': 'tap the naughty cat!',
      'hint_door': 'tap the door',
      'hint_toy': 'tap the sofa',
    },
  };
}
